config/routes.rb
Rails.application.routes.draw do
  resources :fuels
  resources :exercise_types
  resources :exercises
  resources :steps
  resources :weights

  root 'dashboard#index'
  get 'dashboard/show'

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  validates :date, uniqueness: true

  # Average weight over all time
  def self.average_weight
    self.all.sum(:weight) / self.count
  end

  # Average weight this week
  def self.average_weight_week
    week = self.where(date: (Date.today - 7.days)..Date.today)
    if week.count == 0
      "No data"
    else
      week.sum(:weight) / week.count
    end
  end

  # Daily entries over the past week
  def self.daily_weight_week(date)
    today = Date.today - date.days
    if Weight.count == 0
      "No data to calculate"
    else
      weight = Weight.where(date: today).sum(:weight)
    end
  end
  def self.daily_weight
    if Weight.count == 0
      "No data to calculate"
    else
      weight = Weight.where(date: Date.today).sum(:weight)
    end
  end

  def self.total_weight_week
    weight_week = Weight.where(date: (Date.today - 7.days)..Date.today)
    if Weight.count == 0
      "No data to calculate"
    else
      weight_week.sum(:weight)
    end
  end

end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: [:show, :edit, :update, :destroy]

  # GET /weights
  def index
    @weights = Weight.all
  end

  # GET /weights/1
  def show
  end

  # GET /weights/new
  def new
    @weight = Weight.new
  end

  # GET /weights/1/edit
  def edit
  end

  # POST /weights
  def create
    @weight = Weight.new(weight_params)
    respond_to do |format|
      if @weight.save
        format.html { redirect_to @weight, notice: 'Weight was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /weights/1
  def update
    respond_to do |format|
      if @weight.update(weight_params)
        format.html { redirect_to @weight, notice: 'Weight was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /weights/1
  def destroy
    @weight.destroy
    respond_to do |format|
      format.html { redirect_to weights_url, notice: 'Weight was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight
      @weight = Weight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_params
      params.require(:weight).permit(:weight, :date)
    end
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/weights/_form.html.erb
<%= form_for(@weight) do |f| %>
  <% if @weight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weight.errors.count, "error") %> prohibited this weight from being saved:</h2>

      <ul>
      <% @weight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weights/edit.html.erb
<h1>Editing Weight</h1>

<%= render 'form' %>

<%= link_to 'Show', @weight %> |
<%= link_to 'Back', weights_path %>

app/views/weights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weights</h1>

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weights.each do |w| %>
      <tr>
        <td><%= w.weight %></td>
        <td><%= w.date %></td>
        <td><%= link_to 'Show', weight %></td>
        <td><%= link_to 'Edit', edit_weight_path(weight) %></td>
        <td><%= link_to 'Destroy', weight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weight', new_weight_path %>

app/views/weights/new.html.erb
<h1>New Weight</h1>

<%= render 'form' %>

<%= link_to 'Back', weights_path %>

app/views/weights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @weight.weight %>
</p>

<p>
  <strong>Date:</strong>
  <%= @weight.date %>
</p>

<%= link_to 'Edit', edit_weight_path(@weight) %> |
<%= link_to 'Back', weights_path %>