config/routes.rb
Rails.application.routes.draw do
  resources :fuels
  resources :exercise_types
  resources :exercises
  resources :steps
  resources :weights

  root 'dashboard#index'
  get 'dashboard/show'

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]

  # GET /exercises
  def index
    @exercises = Exercise.all
  end

  # GET /exercises/1
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /exercises/1
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /exercises/1
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:exercise_type_id, :burn, :date, :time_spent)
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exercise_type_id %><br>
    <%= f.select :exercise_type_id, options_for_select([["Endurance", 1], ["Strength", 2], ["Flexibility", 3], ["Balance", 4]]) %>
  </div>
  <div class="field">
    <%= f.label :burn %><br>
    <%= f.number_field :burn %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time_spent %><br>
    <%= f.number_field :time_spent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exercises</h1>

<table>
  <thead>
    <tr>
      <th>Exercise type</th>
      <th>Burn</th>
      <th>Date</th>
      <th>Time spent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.exercise_type_id %></td>
        <td><%= exercise.burn %></td>
        <td><%= exercise.date %></td>
        <td><%= exercise.time_spent %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise', new_exercise_path %>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exercise type:</strong>
  <%= @exercise.exercise_type_id %>
</p>

<p>
  <strong>Burn:</strong>
  <%= @exercise.burn %>
</p>

<p>
  <strong>Date:</strong>
  <%= @exercise.date %>
</p>

<p>
  <strong>Time spent:</strong>
  <%= @exercise.time_spent %>
</p>

<%= link_to 'Edit', edit_exercise_path(@exercise) %> |
<%= link_to 'Back', exercises_path %>