config/routes.rb
Rails.application.routes.draw do
  resources :fuels
  resources :exercise_types
  resources :exercises
  resources :steps
  resources :weights

  root 'dashboard#index'
  get 'dashboard/show'

end

app/models/fuel.rb
class Fuel < ActiveRecord::Base

  def self.calories
    Fuel.all.reduce(0) { |s, c| s + c.calorie }
  end

  def self.net_calories
    c = Fuel.all.reduce(0) { |s, c| s + c.calorie }
    b = Exercise.all.reduce(0) { |s, c| s + c.burn }
    c - b
  end

  def self.net_calories_today
    today = Date.today
    if Fuel.count == 0 || Exercise.count == 0
      "No data to calculate"
    else
      fuel = Fuel.where(date: today).sum(:calorie)
      burn = Exercise.where(date: today).sum(:burn)
      fuel - burn
    end
  end

  def self.daily_calories_week(date)
    today = Date.today - date.days
    if Fuel.count == 0 || Exercise.count == 0
      "No data to calculate"
    else
      fuel = Fuel.where(date: today).sum(:calorie)
    end
  end

  def self.week_total_cals
    fuel_week = Fuel.where(date: (Date.today - 7.days)..Date.today)
    if Fuel.count == 0 || Exercise.count == 0
      "No data to calculate"
    else
    fuel_week.sum(:calorie)
    end
  end

  def self.daily_calories
    if Fuel.count == 0 || Exercise.count == 0
      "No data to calculate"
    else
      cals = Fuel.where(date: Date.today).sum(:calorie)
    end
  end

  def self.average_fuel_week
    week = self.where(date: (Date.today - 7.days)..Date.today)
    if week.count == 0
      "No data"
    else
      week.sum(:calorie) / week.count
    end
  end

  def self.net_calories_week
    fuel_week = Fuel.where(date: (Date.today - 7.days)..Date.today)
    exercise_week =  Exercise.where(date: (Date.today - 7.days)..Date.today)
    if Fuel.count == 0 || Exercise.count == 0
      "No data to calculate"
    else
      fuel = fuel_week.sum(:calorie)
      burn = exercise_week.sum(:burn)
      fuel - burn
    end
  end

  def self.net_calories
    c = Fuel.all.reduce(0) { |s, c| s + c.calorie }
    b = Exercise.all.reduce(0) { |s, c| s + c.burn }
    c - b
  end

end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  before_action :set_fuel, only: [:show, :edit, :update, :destroy]

  # GET /fuels
  def index
    @fuels = Fuel.all
  end

  # GET /fuels/1
  def show
  end

  # GET /fuels/new
  def new
    @fuel = Fuel.new
  end

  # GET /fuels/1/edit
  def edit
  end

  # POST /fuels
  def create
    @fuel = Fuel.new(fuel_params)

    respond_to do |format|
      if @fuel.save
        format.html { redirect_to @fuel, notice: 'Fuel was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /fuels/1
  def update
    respond_to do |format|
      if @fuel.update(fuel_params)
        format.html { redirect_to @fuel, notice: 'Fuel was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /fuels/1
  def destroy
    @fuel.destroy
    respond_to do |format|
      format.html { redirect_to fuels_url, notice: 'Fuel was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel
      @fuel = Fuel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuel_params
      params.require(:fuel).permit(:calorie, :date, :food, :meal_type)
    end
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/views/fuels/_form.html.erb
<%= form_for(@fuel) do |f| %>
  <% if @fuel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fuel.errors.count, "error") %> prohibited this fuel from being saved:</h2>

      <ul>
      <% @fuel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calorie %><br>
    <%= f.number_field :calorie %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :food %><br>
    <%= f.text_field :food %>
  </div>
  <div class="field">
    <%= f.label :meal_type %><br>
    <%= f.text_field :meal_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fuels/edit.html.erb
<h1>Editing Fuel</h1>

<%= render 'form' %>

<%= link_to 'Show', @fuel %> |
<%= link_to 'Back', fuels_path %>

app/views/fuels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fuels</h1>

<table>
  <thead>
    <tr>
      <th>Calorie</th>
      <th>Date</th>
      <th>Food</th>
      <th>Meal type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fuels.each do |fuel| %>
      <tr>
        <td><%= fuel.calorie %></td>
        <td><%= fuel.date %></td>
        <td><%= fuel.food %></td>
        <td><%= fuel.meal_type %></td>
        <td><%= link_to 'Show', fuel %></td>
        <td><%= link_to 'Edit', edit_fuel_path(fuel) %></td>
        <td><%= link_to 'Destroy', fuel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuel', new_fuel_path %>

app/views/fuels/new.html.erb
<h1>New Fuel</h1>

<%= render 'form' %>

<%= link_to 'Back', fuels_path %>

app/views/fuels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calorie:</strong>
  <%= @fuel.calorie %>
</p>

<p>
  <strong>Date:</strong>
  <%= @fuel.date %>
</p>

<p>
  <strong>Food:</strong>
  <%= @fuel.food %>
</p>

<p>
  <strong>Meal type:</strong>
  <%= @fuel.meal_type %>
</p>

<%= link_to 'Edit', edit_fuel_path(@fuel) %> |
<%= link_to 'Back', fuels_path %>